# Classification(분류)


### Logistic Regression

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
iris
# data, target, target_names, DESCR, feature_names 들이 있음을 확인할 수 있다.

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
data = iris.data
label = iris.target
columns = iris.feature_names
df = pd.DataFrame(data, columns = columns)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(data,label, test_size = 0.2, shuffle=True, stratify = label, random_state = 2019)

- 모델 객체 생성

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

- 모델 학습

In [8]:
lr.fit(x_train, y_train)

LogisticRegression()

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(verbose = 1)
lr.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(verbose=1)

##### - 학습한 결과를 저장

In [10]:
import joblib
joblib.dump(lr, 'model/iris_lr.pkl')

['model/iris_lr.pkl']

### Support Vector Machine

In [12]:
from sklearn.svm import SVC
svc = SVC()  #객체 생성            ##########################순서 익히기 1

In [13]:
svc

SVC()

In [14]:
svc.fit(x_train,y_train) #학습                ##########################순서 익히기 2

SVC()

In [20]:
import joblib
joblib.dump(svc, 'model/iris_svm.pkl')

['model/iris_svm.pkl']

### Disicion Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [17]:
dtc

DecisionTreeClassifier()

In [18]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [21]:
import joblib
joblib.dump(dtc, 'model/iris_dt.pkl')

['model/iris_dt.pkl']

##### 저장된 모델로 정확도 산출

In [23]:
model_lr = joblib.load('model/iris_lr.pkl')
model_svm = joblib.load('model/iris_svm.pkl')
model_dt = joblib.load('model/iris_dt.pkl')

In [24]:
y_pred_lr = model_lr.predict(x_test)
y_pred_svm = model_svm.predict(x_test)
y_pred_dt = model_dt.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
acc_lr = accuracy_score(y_test, y_pred_lr)
acc_svm = accuracy_score(y_test, y_pred_svm)
acc_dt = accuracy_score(y_test, y_pred_dt)
print(acc_lr,acc_svm,acc_dt)

0.9666666666666667 0.9666666666666667 0.9666666666666667


#### 한개의 테스트 값 예측

In [29]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [35]:
test_data = np.array([6.7, 3.0, 5.2, 2.3]).reshape(1,4)

In [36]:
model_lr.predict(test_data)   ##결과 : 예측한 값이 2라는 뜻, setosa : 0, versicolor : 1, virginica :2

array([2])

In [38]:
index_lr = model_lr.predict(test_data)[0]
index_svm = model_svm.predict(test_data)[0]
index_dt = model_dt.predict(test_data)[0]

In [39]:
sp_names = ['Setosa','Versicolor', 'Virginica']
print(sp_names[index_lr],sp_names[index_svm],sp_names[index_dt])

Virginica Virginica Virginica


### Deep Learning Model

In [48]:
# 딥러닝 모델 설정
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(12, input_shape = (4,), activation = 'relu'),
    Dense(8, input_shape = (4,), activation = 'relu'),
    Dense(3, activation = 'softmax')
])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 12)                60        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 191
Trainable params: 191
Non-trainable params: 0
_________________________________________________________________


In [49]:
# 모델 컴파일
model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [50]:
from keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(filepath="model/iris_deep.hdf5",
                              monitor='val_loss',
                              verbose= 1, save_best_only = True)

In [51]:
# 원핫인코딩
Y_encoded = keras.utils.to_categorical(y_train)
Y_encoded[0],Y_encoded[50],Y_encoded[100]

(array([1., 0., 0.], dtype=float32),
 array([0., 0., 1.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [56]:
#모델학습
model.fit(x_train, Y_encoded, epochs = 100, batch_size = 30, verbose = 2,
         validation_split = 0.2, callbacks = [checkpointer])

Train on 96 samples, validate on 24 samples
Epoch 1/100
 - 0s - loss: 1.4164 - accuracy: 0.3125 - val_loss: 1.2869 - val_accuracy: 0.4167

Epoch 00001: val_loss improved from inf to 1.28690, saving model to model/iris_deep.hdf5
Epoch 2/100
 - 0s - loss: 1.3723 - accuracy: 0.3125 - val_loss: 1.2714 - val_accuracy: 0.4167

Epoch 00002: val_loss improved from 1.28690 to 1.27141, saving model to model/iris_deep.hdf5
Epoch 3/100
 - 0s - loss: 1.3408 - accuracy: 0.3125 - val_loss: 1.2527 - val_accuracy: 0.3750

Epoch 00003: val_loss improved from 1.27141 to 1.25270, saving model to model/iris_deep.hdf5
Epoch 4/100
 - 0s - loss: 1.3139 - accuracy: 0.3125 - val_loss: 1.2295 - val_accuracy: 0.3750

Epoch 00004: val_loss improved from 1.25270 to 1.22953, saving model to model/iris_deep.hdf5
Epoch 5/100
 - 0s - loss: 1.2851 - accuracy: 0.3125 - val_loss: 1.2031 - val_accuracy: 0.3750

Epoch 00005: val_loss improved from 1.22953 to 1.20311, saving model to model/iris_deep.hdf5
Epoch 6/100
 - 0s - 


Epoch 00044: val_loss improved from 0.68726 to 0.67940, saving model to model/iris_deep.hdf5
Epoch 45/100
 - 0s - loss: 0.6962 - accuracy: 0.9062 - val_loss: 0.6698 - val_accuracy: 1.0000

Epoch 00045: val_loss improved from 0.67940 to 0.66981, saving model to model/iris_deep.hdf5
Epoch 46/100
 - 0s - loss: 0.6859 - accuracy: 0.9062 - val_loss: 0.6577 - val_accuracy: 1.0000

Epoch 00046: val_loss improved from 0.66981 to 0.65770, saving model to model/iris_deep.hdf5
Epoch 47/100
 - 0s - loss: 0.6772 - accuracy: 0.8854 - val_loss: 0.6464 - val_accuracy: 0.9167

Epoch 00047: val_loss improved from 0.65770 to 0.64635, saving model to model/iris_deep.hdf5
Epoch 48/100
 - 0s - loss: 0.6651 - accuracy: 0.8854 - val_loss: 0.6395 - val_accuracy: 1.0000

Epoch 00048: val_loss improved from 0.64635 to 0.63945, saving model to model/iris_deep.hdf5
Epoch 49/100
 - 0s - loss: 0.6548 - accuracy: 0.9062 - val_loss: 0.6367 - val_accuracy: 1.0000

Epoch 00049: val_loss improved from 0.63945 to 0.63668


Epoch 00089: val_loss did not improve from 0.37382
Epoch 90/100
 - 0s - loss: 0.3813 - accuracy: 0.9375 - val_loss: 0.3715 - val_accuracy: 1.0000

Epoch 00090: val_loss improved from 0.37382 to 0.37150, saving model to model/iris_deep.hdf5
Epoch 91/100
 - 0s - loss: 0.3724 - accuracy: 0.9375 - val_loss: 0.3603 - val_accuracy: 1.0000

Epoch 00091: val_loss improved from 0.37150 to 0.36028, saving model to model/iris_deep.hdf5
Epoch 92/100
 - 0s - loss: 0.3686 - accuracy: 0.9479 - val_loss: 0.3477 - val_accuracy: 1.0000

Epoch 00092: val_loss improved from 0.36028 to 0.34775, saving model to model/iris_deep.hdf5
Epoch 93/100
 - 0s - loss: 0.3632 - accuracy: 0.9375 - val_loss: 0.3414 - val_accuracy: 1.0000

Epoch 00093: val_loss improved from 0.34775 to 0.34136, saving model to model/iris_deep.hdf5
Epoch 94/100
 - 0s - loss: 0.3600 - accuracy: 0.9375 - val_loss: 0.3344 - val_accuracy: 1.0000

Epoch 00094: val_loss improved from 0.34136 to 0.33443, saving model to model/iris_deep.hdf5
Epo

In [58]:
from keras.models import load_model
model_deep = load_model("model/iris_deep.hdf5")

In [60]:
model.evaluate(x_test, keras.utils.to_categorical(y_test))[1]

30/30 [==============================] - 0s 33us/step


1.0

In [63]:
model_deep.predict_classes(test_data)[0]

2

In [62]:
model_deep.predict(test_data)

array([[0.02312206, 0.37509903, 0.6017788 ]], dtype=float32)

In [61]:
np.argmax(model_deep.predict(test_data)[0])

2